#!/system/bin/sh

mkdir /mnt/cust1
busybox mount -o loop,rw /.cust_backup/image/cust.img /mnt/cust1
rm /mnt/cust1/channel/ru/app/yandexmaps.apk
rm /mnt/cust1/channel/ru/lib/libyandexmaps.so
rm /mnt/cust1/channel/ru/media/bootanimation*.zip
busybox umount /mnt/cust1